name: CommandsXL
main: io.github.dre2n.commandsxl.CommandsXL
version: ${project.version}
author: Daniel Saukel
description: ${project.description}
website: ${project.url}
commands:
  commandsxl:
    description: Custom linked command.
    aliases: [linked,li,l,cxl]
